# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webshop-client

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_066a3069b9b44ef88e656a48ef8b52e5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9723fe1f1205406183185c3e3153ac23 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_066a3069b9b44ef88e656a48ef8b52e5 }}/webshop-client:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webshop-client'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_36078a90f89948abbe193e9e0907e0fd }}
        images: '${{ secrets.AzureAppService_ContainerUsername_066a3069b9b44ef88e656a48ef8b52e5 }}/webshop-client:${{ github.sha }}'
